// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSnippet(arg1) {
  return window['go']['main']['App']['CreateSnippet'](arg1);
}

export function CreateSnippetsFile() {
  return window['go']['main']['App']['CreateSnippetsFile']();
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetSnippetsStoragePath() {
  return window['go']['main']['App']['GetSnippetsStoragePath']();
}

export function PickExistingSnippetsFile() {
  return window['go']['main']['App']['PickExistingSnippetsFile']();
}

export function SetSnippetsStoragePath(arg1) {
  return window['go']['main']['App']['SetSnippetsStoragePath'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['main']['App']['UpdateSnippet'](arg1);
}
