// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateSnippet(arg1:domain.CreateSnippetInput):Promise<domain.Snippet>;

export function CreateSnippetsFile():Promise<string>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function GetCloseToTrayEnabled():Promise<boolean>;

export function GetSnippets():Promise<Array<domain.Snippet>>;

export function GetSnippetsStoragePath():Promise<string>;

export function GetTraySnippetLimit():Promise<number>;

export function PickExistingSnippetsFile():Promise<string>;

export function SetCloseToTrayEnabled(arg1:boolean):Promise<void>;

export function SetSnippetsStoragePath(arg1:string):Promise<string>;

export function SetTraySnippetLimit(arg1:number):Promise<void>;

export function UpdateSnippet(arg1:domain.Snippet):Promise<domain.Snippet>;
