// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateSnippet(arg1:domain.CreateSnippetInput):Promise<domain.Snippet>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function GetSnippets():Promise<Array<domain.Snippet>>;

export function UpdateSnippet(arg1:domain.Snippet):Promise<domain.Snippet>;
